dist: trusty
sudo: false

language: php

addons:
  postgresql: "9.4"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - phpenv config-add travisphp.ini
  - psql -c 'create database testing;' -U postgres
  - mysql -e 'CREATE DATABASE testing;'
  - cp tests/Config.php.travis tests/Config.php

script:
  - curl https://phar.phpunit.de/phpunit-4.8.phar -L -o phpunit.phar && chmod +x phpunit.phar
  - php phpunit.phar
